encyclopedia/urls.py
from django.urls import path

from . import views
app_name="encyclo"
urlpatterns = [
    path("", views.index, name="index"),
    #path("wiki/", views.wiki, name="wiki"),
    
    path("wiki/<str:title>", views.title,name="title"),
    path("search/", views.search,name="search"),
    path("add_page/", views.createnewpg,name="createnewpg"),
    path("check/", views.check,name="check"),
    path("edit/<str:title_name>", views.editpage,name="editpage"),
    path("/random", views.randompage,name="randompage")
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls")),
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
import markdown2
from django.urls import reverse
from . import util
from django.shortcuts import redirect
from django import forms
import random


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })
#def wiki(request):
 #   return HttpResponse("nothing on this page")

def title(request,title):
    content=util.get_entry(title)
    if content==None:
        return render(request,"encyclopedia/pagenotfound.html",{
            "content" :["Page Not Found !!"]
        })
    else:
        content_html=markdown2.markdown(content)
        return render(request,"encyclopedia/info.html",{
            "title" :title,
            "content" :content_html
        })
#class SearchForm(forms.Form):
 #   query=forms.CharField()

def search(request):
    query = request.GET.get("q", "")
    entries = util.list_entries()
    if query:
        if query in entries:
            """content = util.get_entry(query)
            content_html = markdown2.markdown(content)
            return render(request, "encyclopedia/info.html", {
                "title": query,
                "content": content_html
            })"""
            return HttpResponseRedirect(reverse("encyclo:title",args=[query]))
        else:
            listy = [entry for entry in entries if query.lower() in entry.lower()]
            if listy:
                return render(request, "encyclopedia/search.html", {
                    "query": query,
                    "entries": listy
                })
            else:
                return render(request,"encyclopedia/pagenotfound.html",{
                    "content" :["No page named" , query,"!!"]
                })
                
    else:
        current_page = request.META.get('HTTP_REFERER')
        return redirect(current_page)
class newentries(forms.Form):
    new_entry=forms.CharField() 
    content=forms.CharField(widget=forms.Textarea(attrs={
        'class':'custom_textarea'
    }))
def createnewpg(request):
    return render(request,"encyclopedia/createnewpage.html",{
        "title" :"create_new_page",
        "form" :newentries()

    })
def check(request):
    entries=util.list_entries()
    if request.method=="POST":
        form=newentries(request.POST)
        if form.is_valid():
            pagename=form.cleaned_data['new_entry']
            for entry in entries:
                if pagename.lower() == entry.lower():
                    form.add_error("new_entry","This page already exists")
                    return render(request,"encyclopedia/createnewpage.html",{
                        "title" :"Create_new_page",
                        "form" :form
                    })


            content= form.cleaned_data['content']
            util.save_entry(pagename ,content)
            return redirect(reverse("encyclo:title",args=[pagename]))
        else:
            return render(request,"encyclopedia/createnewpage.html",{
                "title" :"Create_new_page",
                "form" :newentries()
            })
    else:
        
        return render(request,"encyclopedia/createnewpage.html",{
            "title" :"Create_new_page",
            "form" :newentries()
        })
class editing(forms.Form):
    do_edit=forms.CharField(widget=forms.Textarea(attrs={
        'class':'custom_textarea'
    }))

def editpage(request,title_name):
    if request.method=="POST":
        form=editing(request.POST)
        if form.is_valid():
            edit=form.cleaned_data['do_edit']
            edit_html=markdown2.markdown(edit)
            util.save_entry(title_name,edit_html)
            return HttpResponseRedirect(reverse("encyclo:title",args=[title_name]))
    else:
        data={"do_edit": util.get_entry(title_name)}
        return render(request,"encyclopedia/edit.html",{
            "title" :title_name,
            "form" :editing(initial=data)
        })


def randompage(request):
    entries=util.list_entries()
    title=random.choice(entries)

    return HttpResponseRedirect(reverse("encyclo:title",args=[title]))

encyclopedia/templates/encyclopedia/createnewpage.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}
{% block body %}
<form action="{% url 'encyclo:check' %}" method="post">

    {% csrf_token %}
    <br>
    {{ form }}
    <br>
    {{ content }}
    <br>
    <input type="submit" value="add page" name="submit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}
{% block body %}
<form action="{% url 'encyclo:editpage' title_name=title %}" method="post">
    {% csrf_token %}
    {{ form }}
    <br>
    <input type="submit" value="save changes" name="change">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}

                <li><a href="{% url 'encyclo:title' title=entry %}" >{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/info.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}
{% block body %}
{{ content|safe }}
<a style="top: 10px; right: 10px; position: absolute;padding-top: 10px; padding-right: 30px;" href="{% url 'encyclo:editpage' title_name=title %}">edit page</a>
{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclo:search' %}" method="get">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclo:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclo:createnewpg' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclo:randompage' %}" >Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/pagenotfound.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}
{% block body %}
<div>
    <h1>
        {% for con in content %}
            {{ con }}
        {% endfor %}
    </h1>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
{{ title }}
{% endblock %}
{% block body %}
<div>
    <ul>
        {% for list in entries %}
            <li><a href="http://127.0.0.1:8000/wiki/{{ list }}">{{ list }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}